# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Quasbot

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python and Node.js
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Change working directory to quasmati-portal
      - name: Change working directory
        run: cd quasmati-portal

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deploy the code using the serverless framework
      - name: Deploy code
        run: |
          npm install -g serverless@latest
          sls deploy -v







